export const DISPATCH_ACTION = 'DISPATCH_ACTION';

export const START_LOAD = 'START_LOAD';
export const FINISH_LOAD = 'FINISH_LOAD';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';

export const PROCESS_ADD_PRODUCT = 'PROCESS_ADD_PRODUCT';
export const PROCESS_REMOVE_PRODUCT = 'PROCESS_REMOVE_PRODUCT';
export const PROCESS_CLEAR_CART = 'PROCESS_CLEAR_CART';

export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const CLEAR_CART = 'CLEAR_CART';
