// Auth Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const REFRESH_USER_TOKEN = 'REFRESH_USER_TOKEN';

export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';

// Cart Types
export const PROCESS_ADD_PRODUCT = 'PROCESS_ADD_PRODUCT';
export const PROCESS_REMOVE_PRODUCT = 'PROCESS_REMOVE_PRODUCT';
export const PROCESS_CLEAR_CART = 'PROCESS_CLEAR_CART';

export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const SET_CART = 'SET_CART';
export const SET_AMOUNT = 'SET_AMOUNT';

// Filters Types

export const APPLY_FILTER = 'APPLY_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
